### PR TITLE
add fully python support for 2022

### PR DESCRIPTION
**Pull request by jensfraedrich**
In PAP for 2022 is an empty if statement (following bei an else statement), which is not supported in python.
So I inverted the contition an give all else expressions to the then statement (which was empty before).

### CODE REVIEW

**Comment by jenner** [comment]
Hi, could you provide an example please?

**Comment by jenner** [comment]
> Hi, could you provide an example please?

Nevermind, found it

**Comment by jenner** [comment]
@jensfraedrich It's easier to add a `pass` statement here then invert the whole if-condition logic, I'll add a patch asap

**Comment by jenner** [comment]
Fixed in be2f995

**Comment by jensfraedrich** [comment]
> @jensfraedrich It's easier to add a `pass` statement here then invert the whole if-condition logic, I'll add a patch asap

Of course you're right, I found the result just nicer.

**Pull request closed without merging**
